### ISSUE TITLE
diffAdded and diffRemoved are unreadable

### ISSUE THREAD

**Issue by Kavantix** [luisiacc/gruvbox-baby#1]
Hi @luisiacc I'm really enjoying your theme.
I'm just experiencing one problem, the diffAdded and diffRemoved highlighting have a very dark foregroundColor which makes it unreadable.
As a workaround I have linked them to DiffAdd and DiffRemove (so it makes the background color green/red instead of the foreground) But you probably can come up with a better color scheme ;)

**Comment by luisiacc** [comment]
Thank you for your suggestion, I'll check it out.

**Comment by luisiacc** [comment]
I've modified the foreground colors, Hope you can enjoy it now!

**Comment by Kavantix** [comment]
That looks amazing thanks!
