### ISSUE TITLE
Background colour contrast

### ISSUE THREAD

**Issue by robbienohra** [luisiacc/gruvbox-baby#11]
Some highlight groups seem to be rendering a little lighter than the background colour 🤔 

Notice `main` or `printf` or `assert`

<img width="414" alt="image" src="https://user-images.githubusercontent.com/28514482/154830268-3d5d2a9b-638b-4efe-ada0-c2b42889ccb8.png">

**Comment by robbienohra** [comment]
For what it's worth I'm only currently observing this in `.cpp` files (not seeing this in `.js` or `.ts` files)

**Comment by ViRu-ThE-ViRuS** [comment]
same! was just about to file.

**Comment by luisiacc** [comment]
Fixed! Thanks for reporting it!

**Comment by robbienohra** [comment]
Np, thanks for the quick turnaround! 🙇

Kudos to you for this theme btw — I think that a gruvbox reboot has been long overdue! I really resonated with your sentiment that the current available colour palettes are lacking! Wishing you the best 👍
