### ISSUE TITLE
Wrong color code in palette image in README.md

### ISSUE THREAD

**Issue by feekApp** [luisiacc/gruvbox-baby#15]
Hi,

In your image of the gruvbox-baby color palette in README.md you have set a wrong hex color code for gray.

![img](https://feek.d.pr/2J3lyN/ILxltmtzdo.jpg)

It should be #DEDEDE.

== Feek

**Comment by crzdg** [comment]
@luisiacc 

I think this can be closed now. :-)

**Comment by feekApp** [comment]
indeed!
