### ISSUE TITLE
Html Tag brackets are not good visible

### ISSUE THREAD

**Issue by feekApp** [luisiacc/gruvbox-baby#16]
Hi when using Treesitter, the HTML tag brackets are not good visible:
![img](https://feek.d.pr/gsgtUJ/ZYQi1G3ZVG.jpg)

Could you please change on line 132 of `theme.lua` to the following:

`TSTagDelimiter = { fg = c.forest_green },`

It will become like:
![img2](https://feek.d.pr/ekbzjp/sGxDgTXy6J.jpg)

Now the color is set to `c.comment`.

**Comment by luisiacc** [comment]
Hi there, sorry for the late comment, I kind of like the color as is currently set, there is a easy way to change it on your own config which is to do this:

```lua
local colors = require("gruvbox-baby.colors").config()
vim.g.gruvbox_baby_highlights = {TSTagDelimiter = {fg = colors.forest_green}}
```

**Comment by feekApp** [comment]
Thnx. Based on your suggestion I've made my own tweaks :-)
