### ISSUE TITLE
Issue and suggestions

### ISSUE THREAD

**Issue by sabah1994** [luisiacc/gruvbox-baby#19]
Issue

1) Cursor colour is very dark and hard to see on any empty space before text. See image below

![Screenshot from 2022-08-03 00-46-36](https://user-images.githubusercontent.com/73726199/182495702-8ea1854f-b05c-481b-b287-d2d14e530e51.png)

Expectation (it seems to be fine after some text)

![Screenshot from 2022-08-03 00-51-15](https://user-images.githubusercontent.com/73726199/182495832-39c1dbd7-5b4f-484e-b78e-ab5739c39ff7.png)

Note: This problem is on Ubuntu terminal  and Mac (iterm 2) seems to be fine.

Suggestion;
I'm using CoC.nvim, CursorHold (which highlights the symbol and references) and visually highlighted text share very similar (if not same)  highlight group so it's hard to tell when I'm in visual mode. 
I have changed it for myself but maybe this should be addressed in the colour scheme. 

Overall, I'm loving this theme, I have been using gruvbox for over a year but it just didn't seem enough for Python, Lua and JS.
Thank you again.

**Comment by luisiacc** [comment]
> I have been using gruvbox for over a year but it just didn't seem enough for Python, Lua and JS.

Those were my exact thoughts when creating this theme!

> Cursor colour is very dark and hard to see on any empty space before text. See image below

Personally I like it the way it is, so called it to "personal choice"

> I'm using CoC.nvim, CursorHold (which highlights the symbol and references) and visually highlighted text share very similar (if not same) highlight group so it's hard to tell when I'm in visual mode.

I don't use coc, could you provide a picture of it so I can improve it?

**Comment by sabah1994** [comment]
> Personally I like it the way it is, so called it to "personal choice"
Is there a simple way of changing it?

> I don't use coc, could you provide a picture of it so I can improve it?
![Screenshot from 2022-08-03 10-03-00](https://user-images.githubusercontent.com/73726199/182570345-b418455f-0eff-4ea0-b0a7-64b303a75bf4.png)

I have visually select the word under cursor but as you can see it's very similar to other reference and definition.
The highlight group for CocCursorHold is "CocHighlightText" and is linked to "CursorColumn"
![Screenshot from 2022-08-03 10-11-30](https://user-images.githubusercontent.com/73726199/182571143-2478c36f-f1bd-484e-8aa3-8b0084d816fc.png)

**Comment by luisiacc** [comment]
> Is there a simple way of changing it?

Hmm looking closely I have no idea why it's a color before text and a color after, have you tried what happens on another terminal emulator?

**Comment by sabah1994** [comment]
No idea why, on Ubuntu I tried in and out of tmux and it still persists.
Could I run some test to see what highlight group is being used there (under the cursor)?

**Comment by luisiacc** [comment]
> Could I run some test to see what highlight group is being used there (under the cursor)?

Don't know if you can do that since there is actually nothing under the cursor.
