### ISSUE TITLE
cursorcolumn not visible

### ISSUE THREAD

**Issue by infinite-ops** [luisiacc/gruvbox-baby#2]
Hi I use cursorcolumn from time to time and I couldnt see how to set its colour or make it so it was visible. For now I'm doing this:
```
❯ git --no-pager diff
diff --git a/lua/gruvbox-baby/theme.lua b/lua/gruvbox-baby/theme.lua
index 4823f2d..14c97e2 100644
--- a/lua/gruvbox-baby/theme.lua
+++ b/lua/gruvbox-baby/theme.lua
@@ -259,7 +259,7 @@ function M.setup(config)
 
     ColorColumn = { bg = c.background_dark },
     SignColumn = { bg = c.background },
-    CursorColumn = { bg = c.background },
+    CursorColumn = { bg = c.bg_light },
```

How should I be overriding this?

btw love the colour scheme its awesome!

**Comment by luisiacc** [comment]
Hi there, thank you for your kind words!, That's the correct way of doing it, in the future I will add an option to override some fields, I noticed that `CursorColumn` has the same background as the `Normal` background, so it's not visible, I will correct it.
