### ISSUE TITLE
Telescope theme results prompt title

### ISSUE THREAD

**Issue by oldnicolas** [luisiacc/gruvbox-baby#20]
```
vim.g.gruvbox_baby_telescope_theme = 1
vim.g.gruvbox_baby_transparent_mode = 1
```
<img width="1493" alt="Screen Shot 2022-08-05 at 15 00 30" src="https://user-images.githubusercontent.com/108978801/183020620-e2ca2b20-2d35-4a57-b6ad-6d9a27ead652.png">

**Comment by luisiacc** [comment]
When using the telescope theme, I'd recommend to remove all borders from telescope, becaue otherwise it looks like this.
