### ISSUE TITLE
Colors are off

### ISSUE THREAD

**Issue by urob** [luisiacc/gruvbox-baby#22]
I have no idea why but somehow the colors seem off when using this scheme. I am running nvim 0.6.1 on Debian under WSL2.0 on Windows Terminal.

I have tried to run nvim inside and outside of tmux, with `set termguicolors` on and off, and it always looks the same. I don't have any issues with other colorschemes. 

This colorscheme looks really nice and I'd like to get it to work. If someone has any ideas what to try that would be great.

<img width="721" alt="Screenshot 2022-08-06 165515" src="https://user-images.githubusercontent.com/978080/183265748-9a4c1be6-1498-4284-9ae0-2ce9120b8dc3.png">

**Comment by luisiacc** [comment]
Could you update to the [latest stable version](https://github.com/neovim/neovim/releases/tag/v0.7.2) and try again?

**Comment by urob** [comment]
That did it. Thanks!
