### ISSUE TITLE
Option to italicize the string

### ISSUE THREAD

**Issue by sabah1994** [luisiacc/gruvbox-baby#26]
Just like the original gruvbox, can you add the option `g:gruvbox_italicize_strings` to set italic style for string please?

**Comment by luisiacc** [comment]
Sure, sounds good.

**Comment by sabah1994** [comment]
Thank you.

Three more questions please;
1) Curious if multiple attributes could be passed e.g italic and bold. or is it jut limited to one?

2) Is this how NvimTree is meant to look like? 
![Screenshot from 2022-08-14 00-35-33](https://user-images.githubusercontent.com/73726199/184516712-9545f833-677e-4189-9543-772aef77c54c.png)

3) Also I feel like yellow seems to be dominating, e.g  yellow colour is used for function name, function calling but in original it was orange. can it be changed to orange easily? (One way I can do is in the plug repo, replace yellow with orange) wondering if there is another way?

**Comment by luisiacc** [comment]
> Curious if multiple attributes could be passed e.g italic and bold. or is it jut limited to one?

Yes, you can do this

```lua
vim.g.gruvbox_baby_string_style = {"bold", "italic"}
```

> Is this how NvimTree is meant to look like?

Are you using a specific background color config?

> Also I feel like yellow seems to be dominating, e.g yellow colour is used for function name, function calling but in original it was orange. can it be changed to orange easily? (One way I can do is in the plug repo, replace yellow with orange) wondering if there is another way?

You can change every particular treesitter highlight with this:

```lua
local c = require("gruvbox-baby.colors").config()
vim.g.gruvbox_baby_highlights = {
  TSFunction = {fg = c.orange},
}

```

**Comment by sabah1994** [comment]
Thanks about 1 and 3.

2. I was, I now commented it out (vim.g.gruvbox_baby_highlights) and result is hardly any different.
![Screenshot from 2022-08-14 00-57-44](https://user-images.githubusercontent.com/73726199/184517204-15308165-ce4d-401c-b4cc-9f3265af8938.png)

**Comment by luisiacc** [comment]
> I was, I now commented it out (vim.g.gruvbox_baby_highlights) and result is hardly any different.

Yeah I'm gonna fix that, the color is off when the background is `dark`

**Comment by luisiacc** [comment]
done!

**Comment by sabah1994** [comment]
Thank you!
