### ISSUE TITLE
Visual select color

### ISSUE THREAD

**Issue by nagy135** [luisiacc/gruvbox-baby#27]
Hello, I m having issue with color of visual select.
On the screenshot bellow, line with "scripts" is highlighted in line-select mode.
The color is very close to the background and I dont know how to change it.

Am I doing something wrong or does everyone have this low contrast on highlights?

![image](https://user-images.githubusercontent.com/11056512/185098290-070ea533-78d8-47e8-95f9-6efd4e0427c5.png)

**Comment by luisiacc** [comment]
it definitely should be visible, what background contrast are you using? (soft, medium, dark)

**Comment by jhthorsen** [comment]
I got the same issue when I set `vim.g.gruvbox_baby_transparent_mode = true`.

**Comment by luisiacc** [comment]
Seems like a problem with the transparent mode.

**Comment by luisiacc** [comment]
@nagy135 if you still have the problem, please reopen

**Comment by nagy135** [comment]
I dont think this is understood yet....because ye when I manually change that highlight color it works, and thats what I have now and I have no problem. BUT ...why do I need to do that ? I didnt set no transparent mode, all I did was installing package and putting `vim.cmd[[colorscheme gruvbox-baby]]` at the end of my vim.lua. 

If anyone faces the same problem, this is all you need to do
```lua
-- without these 2 lines highlight is almost invisible {{{
local colors = require('gruvbox-baby.colors').config()
vim.g.gruvbox_baby_highlights = {Visual = {bg = colors.medium_gray}}
-- }}}
vim.cmd[[colorscheme gruvbox-baby]]

```

**Comment by luisiacc** [comment]
I made that color the default so you don't have to do that anymore.
