### ISSUE TITLE
Add support for p00f/nvim-ts-rainbow

### ISSUE THREAD

**Issue by d12bb** [luisiacc/gruvbox-baby#28]
Colors for [p00f/nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow) can be supported with the `rainbowcol[1-7]` highlight color groups: [p00f/nvim-ts-rainbow#91](https://github.com/p00f/nvim-ts-rainbow/issues/91#issuecomment-1030106157)

**Comment by luisiacc** [comment]
I actually have a local implementation of this!, I'll just include it in the plugin.

**Comment by luisiacc** [comment]
Done in https://github.com/luisiacc/gruvbox-baby/commit/c99f37e25ef61226fd7d70dc136ea2f9dd2f3601
