### ISSUE TITLE
how to match with illuminator

### ISSUE THREAD

**Issue by icymankr** [luisiacc/gruvbox-baby#29]
Please refer to  the plugin RRethy/vim-illuminate.
It seems not working with illuminator.

**Comment by luisiacc** [comment]
I don't really use this plugin, I can add it at some point but not soon, if you file a PR for it I'd be more than happy to merge it.

**Comment by postfen** [comment]
Just created a PR for support for vim-illuminate. #30

**Comment by luisiacc** [comment]
Closed in https://github.com/luisiacc/gruvbox-baby/pull/30
