### ISSUE TITLE
Weird color inside tmux

### ISSUE THREAD

**Issue by tabiva** [luisiacc/gruvbox-baby#3]
Hi, there are some weird colors on some keywords, this happens only inside tmux (default conf). I've even tried disabling other plugins. This happens with python, lua and some conf files for sure, didn't tried other file types:

<img width="1336" alt="Schermata 2022-01-21 alle 11 41 55" src="https://user-images.githubusercontent.com/37195010/150513802-a0619bdc-c88d-4aa7-858a-792cbd700b13.png">

**Comment by luisiacc** [comment]
Hi there @tabiva, I have this on my `~/.tmux.conf` to display the right colors:
```
set -ga terminal-overrides ",xterm-256color*:Tc"
set -g default-terminal "xterm-256color"
```

**Comment by luisiacc** [comment]
If you keep having this problem please reopen!

**Comment by tabiva** [comment]
Yeah it worked great! Thank you!
