### ISSUE TITLE
Error theme loading

### ISSUE THREAD

**Issue by ctarx** [luisiacc/gruvbox-baby#36]
I tried to use this theme with _lunarvim_ but it returns an error:
```
Error detected while processing nvim_exec() called at /home/ctarx/.local/share/lunarvim/site/
pack/packer/start/gruvbox-baby/colors/gruvbox-baby.vim:7:
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
```
**Nvim**: v0.8.0-dev

**Comment by luisiacc** [comment]
Could you update your neovim version to latest nightly and try again?

**Comment by ctarx** [comment]
I'm using the latest unstable version v0.8.0-dev, but I don't want to mess with the nightly v0.9.0-dev, as I'm not sure if lunarvim is already running with this version.

**Comment by luisiacc** [comment]
ok, could you try the 0.8 release then?

**Comment by ctarx** [comment]
I tried stable ppa and unstable with 0.8 release, same error.

**Comment by ctarx** [comment]
It started working with NVIM v0.9.0-dev.
