### ISSUE TITLE
Treesitter support broken

### ISSUE THREAD

**Issue by mrdgo** [luisiacc/gruvbox-baby#39]
To actually have treesitter support, this [file](https://gist.github.com/jdrouhard/dccbb692e901d5e0a00a3a4c126079c6) is required.

I hereby request to support treesitter without this workaround.

**Comment by luisiacc** [comment]
Thank you for your suggestion, I'll use it.

**Comment by mrdgo** [comment]
To be honest, I am confused. Instead of fixing the issue, you integrate the workaround to your repo? I mean, this is totally appropriate as a temporary hotfix. However, I feel like the actual issue is not resolved. There is deprecated treesitter API and `ts-fix.lua` acts as an adapter to define hlgroups the old way and make them comply with new API. Is there someone who can do that API upgrade?

**Comment by luisiacc** [comment]
Yes, I have it there until I implement it in the proper way, using the new highlight groups names when defining the colors.

**Comment by mrdgo** [comment]
Out of curiosity: why are people downvoting?
