### ISSUE TITLE
Cursor not visible in search highlight

### ISSUE THREAD

**Issue by cpfaff** [luisiacc/gruvbox-baby#4]
Cursor color and search highlight are the same. That makes it impossible to see the cursor in search results.
![2022-01-22-131821_742x90_scrot](https://user-images.githubusercontent.com/1726483/150638281-697eede1-a659-44dd-8710-2799b27f8844.png)

**Comment by cpfaff** [comment]
Cursor here is on the "s" of sear ;-)

**Comment by cpfaff** [comment]
Apart from that I would really like to thank you for this schema. It is really nicely done.

**Comment by cpfaff** [comment]
OK. I tested a bit. This seems to be related to the terminal emulators I am using. Suckless ST or urxvt. In both the color is nocht correctly to your setup here as the search should be green as saw in the config. I installed alacritty and there it works. Any idea to get it working in the others would be appreciated if you have any idea.

**Comment by luisiacc** [comment]
I'm going to check it out, Some terminals define their own colors for the block cursor, some of them let the current application determinate the color, my guess is the `Cursor` highlight is the same as the search highlight, I haven't seen this because my terminal has her own cursor color.

**Comment by luisiacc** [comment]
Also, some terminals use a `reverse` style for the cursor, curiously the `Search` highlight also uses the reverse style, so they overlap and you don't see the cursor.

**Comment by cpfaff** [comment]
That was what I am investigating into at the moment as well. ;-)

**Comment by luisiacc** [comment]
However, the `IncSearch` highlight of this theme is not `reverse` so it shouldn't be a problem, so it's probably your terminal 😜

**Comment by cpfaff** [comment]
Yeah. I do see the IncSearch as you intended it to be. But as soon as it is a final search result it goes wrong. You are likely right with a default cursor color for the reverse cursor being set in my cases. I just tested it. Changed your theme and the colors used for the highlight of results. Works... So I have to find a way to adjust the reverse cursor color in my terminal emulators.

**Comment by cpfaff** [comment]
Thanks! Anyways.

**Comment by luisiacc** [comment]
Thank for clarifying!

**Comment by cpfaff** [comment]
Welcome.
