### ISSUE TITLE
[Style Change] Remove italic from highlight "Special"

### ISSUE THREAD

**Issue by crzdg** [luisiacc/gruvbox-baby#42]
The `Special` highlight has the style `italic`. This let looks the `\`-character for escapes look like a `|`-character.
I do not know if this is intended.

I would propose to change the style of `Special` to empty/none.

#### Current
![image](https://user-images.githubusercontent.com/4175183/198283827-ce5f9b58-dd4f-4266-8bc4-daa64fe27a8e.png)
![image](https://user-images.githubusercontent.com/4175183/198284051-fd15fa3b-40a5-4d00-8b41-fb357104b830.png)

#### Special with no style
![image](https://user-images.githubusercontent.com/4175183/198283946-24f187b5-886e-4722-808d-3f115bc70e1f.png)
![image](https://user-images.githubusercontent.com/4175183/198284162-df88d34f-434c-437d-abfb-44c70f986f5d.png)

**Comment by crzdg** [comment]
@luisiacc  I interpreted your `thumb-up` as, lets do it!

So I opened a PR for this, see #43

**Comment by luisiacc** [comment]
Closed in https://github.com/luisiacc/gruvbox-baby/pull/43
