### ISSUE TITLE
Search highlight not readable when the matching text is in foreground color and transparent mode is on

### ISSUE THREAD

**Issue by HuabeiYou** [luisiacc/gruvbox-baby#48]
Hi there, first of all thanks for making this colorscheme!

I had problem reading the search result when the original text is in foreground color.
<img width="180" alt="Screen Shot 2022-11-20 at 11 57 10" src="https://user-images.githubusercontent.com/71667151/202915387-b0a2de1e-2efa-443a-85f0-cd3c8ed29b27.png">

After some digging I think it's due to the combination of
```lua
if config.transparent_mode then
  local transparent = {
    background = colors.none,
    background_dark = colors.none,
  }
  colors = vim.tbl_extend("force", colors, transparent)
end
``` 
and
```lua
Search = { fg = c.background, bg = c.foreground }
```

I temporarily fixed it by setting the bg to `medium_gray` in my config.
```lua
Search = { fg = c.background, bg = c.medium_gray }
```
<img width="168" alt="Screen Shot 2022-11-20 at 11 57 43" src="https://user-images.githubusercontent.com/71667151/202918913-15953bcc-63bb-4b86-8112-50835008ec8b.png">

I see there is already a block handling transparent mode configurations
```lua
if config.transparent_mode then
  theme.base = vim.tbl_extend("force", theme.base, {
    Visual = { bg = c.medium_gray },
    MultiCursor = { bg = c.medium_gray },
    Cursor = { bg = c.soft_green, c.dark }
  })
end
```
Maybe `Search` should also be added there

**Comment by sabah1994** [comment]
This Commit messed up Search highlight for me. I can't see any highlighted text instances.
![Screenshot from 2022-12-02 19-18-40](https://user-images.githubusercontent.com/73726199/205369152-f353d2ae-60fa-4322-bcf4-2b91863a50a7.png)

As you can see on the left hand side, all the "Plug" instances are now same colour as background and hidden. Right is what it used to be (I pointed to previous commit and it seems to be working fine.
Plug("luisiacc/gruvbox-baby", {commit = "ea71b4225d0140103d99748ca4a33ecf22c03f62"})

**Comment by sabah1994** [comment]
Another issue if highlight fg is "milk" then unable to read highlighted instances. See screenshot below 
![Screenshot 2022-12-07 at 12 21 45](https://user-images.githubusercontent.com/73726199/206178592-b196c4fb-39e1-48f1-8708-c4a0851db712.png)

**Comment by luisiacc** [comment]
could you check again? I changed it.

**Comment by sabah1994** [comment]
Fixed. thanks
