### ISSUE TITLE
column color missing?

### ISSUE THREAD

**Issue by mil-ad** [luisiacc/gruvbox-baby#52]
Is `hl-columncolor` part of the theme? If yes I don't think it's being set in this repo.

**Comment by luisiacc** [comment]
You mean this ? https://github.com/luisiacc/gruvbox-baby/blob/main/lua/gruvbox-baby/theme.lua#L337

**Comment by mil-ad** [comment]
mmm, I'm not 100% sure. I mean the rulers you'd get with something like `set colorcolumn=81,121`

**Comment by luisiacc** [comment]
yes, that's the one, do you have transparent background?

**Comment by mil-ad** [comment]
I do

**Comment by luisiacc** [comment]
when transparent mode is activated the ColorColumn doesn't show, you can do this to apply another color to the color column though, put this on your config somewhere:

```lua
local c = require("gruvbox-baby.colors").config()
vim.g.gruvbox_baby_highlights = {
  ColorColumn = { c.comment }, -- can be any color you want
}
```

You can check out the palette [here](https://github.com/luisiacc/gruvbox-baby#-palette) or in the code
