### ISSUE TITLE
can the color of 'this' be changed?

### ISSUE THREAD

**Issue by guoliang** [luisiacc/gruvbox-baby#58]
How it is in vscode with gruvbox theme
<img width="285" alt="Screenshot 2023-03-20 at 22 00 24" src="https://user-images.githubusercontent.com/542598/226465007-5865678b-936b-49a2-839d-33818d5d22f4.png">

How it is with gruvbox-baby
<img width="290" alt="image" src="https://user-images.githubusercontent.com/542598/226465178-618070dc-06aa-4a76-8837-a33586846331.png">

**Comment by luisiacc** [comment]
Yes, you can do this:

```lua
local c = require("gruvbox-baby.colors").config()
vim.g.gruvbox_baby_highlights = {
  ["@variable.builtin"] = { fg = c.orange },
}
```
