### ISSUE TITLE
Override highlight comment doesn't work?

### ISSUE THREAD

**Issue by guoliang** [luisiacc/gruvbox-baby#59]
Hi, I have the following setting, and my question is specifically about the override of `comment` which I think should change the text color of comments to orange, but it did not change the color at all.

```lua
{
	"luisiacc/gruvbox-baby",
	branch = "main",
	config = function()
		local colors = require("gruvbox-baby.colors").config()

		vim.o.termguicolors = true
		vim.g.gruvbox_baby_background_color = "medium"
		vim.g.gruvbox_baby_highlights = {
			["@variable.builtin"] = { fg = colors.orange },
			DiagnosticUnderlineError = { sp = "#ff0000", style = "undercurl" },
			LineNr = { fg = "#DEDEDE" },
			CursorLineNr = { fg = "#FFB81C" },
			Comment = { fg = colors.orange },
		}
		vim.g.gruvbox_baby_transparent_mode = 1
	end,
},
```

**Comment by luisiacc** [comment]
Hi, I think it's because the comment highlights are highlighted from the `"@comment"` group, which is the treesitter group(the ones that are used), the `Comment` is the default group.

**Comment by guoliang** [comment]
thanks, I needed to use `@comment`.
