### ISSUE TITLE
Support Galaxyline.nvim

### ISSUE THREAD

**Issue by cpfaff** [luisiacc/gruvbox-baby#6]
He

Color support for Galaxyline would be awesome. I could also help with digging for highlight groups and I would sacrifice testing it of course ;-)

https://github.com/glepnir/galaxyline.nvim

**Comment by luisiacc** [comment]
I don't use galaxyline, from what I've seen it doesn't have a default configuration of where every section go, is more of a `you make your own theme`, so colors should match the feeling of the theme.
You can access the palette via:
```lua
local colors = require("gruvbox-baby.colors").config()
```

and use that colors on your custom theme.
