### ISSUE TITLE
The color tones appear to be broken on MacOS terminal.

### ISSUE THREAD

**Issue by RainYuGG** [luisiacc/gruvbox-baby#60]
The color scheme appears to be severely broken when applied to the default terminal on Mac. It's not just a simple issue of color tones, but rather a complete collapse of the colors.

![Screenshot 2023-04-25 at 8 44 02 PM](https://user-images.githubusercontent.com/31921037/234280084-b66e7039-a450-4b58-97b9-2d7445c6403f.png)

### scheme setting using lua 

```
-- gruvbox-baby config & setting
local colors = require("gruvbox-baby.colors").config()
vim.g.gruvbox_baby_highlights = {Normal = {fg = colors.foreground}}
-- Enable telescope theme
vim.g.gruvbox_baby_telescope_theme = 1
-- Enable transparent mode
vim.g.gruvbox_baby_transparent_mode = 1
vim.cmd[[colorscheme gruvbox-baby]]
```

### neovim version

```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"
```

I'm not sure if the problem is with the terminal, as the colors work correctly when using [morhetz/gruvbox ](https://github.com/morhetz/gruvbox). But it doesn't fit [treesitter](https://github.com/nvim-treesitter/nvim-treesitter).

**Comment by RainYuGG** [comment]
I figure out the problem, it seems to be the terminal problem.

https://github.com/vim/vim/issues/993

**Comment by luisiacc** [comment]
Cool, fwiw I recommend this terminal https://github.com/wez/wezterm . It has everything plus it's fast.
