### ISSUE TITLE
maybe need a feature "type_style" to support Structures and Interfaces in Golang

### ISSUE THREAD

**Issue by forbearing** [luisiacc/gruvbox-baby#61]

**Comment by forbearing** [comment]
<img width="593" alt="Screenshot 2023-05-05 at 08 06 25" src="https://user-images.githubusercontent.com/22474410/236355108-6bac692f-90d3-4969-ba22-83348c602688.png">
<img width="768" alt="Screenshot 2023-05-05 at 08 05 58" src="https://user-images.githubusercontent.com/22474410/236355115-ce90a601-cd0b-4e09-a775-ffbfa251fd54.png">

**Comment by forbearing** [comment]
Here is my gruvbox_baby theme config

<img width="448" alt="Screenshot 2023-05-05 at 08 10 29" src="https://user-images.githubusercontent.com/22474410/236355314-a75f668a-e70e-45b6-8f97-835815378ced.png">

**Comment by luisiacc** [comment]
Hi there, temporarily you could do this:

```lua
local c = require("gruvbox-baby.colors").config()
vim.g.gruvbox_baby_highlights = {
  ["@type"] = { fg = c.clean_green, style = "italic" },
  ["@type.builtin"] = { fg = c.blue_gray, style = "italic" },
  ["@type.qualifier"] = { fg = c.orange, style = "italic" },
  ["@type.definition"] = { fg = c.soft_yellow, style = "italic" },
}
```

Replace `italic` with your style.
