### ISSUE TITLE
Unable to affect Pmenu colour

### ISSUE THREAD

**Issue by bitwombat** [luisiacc/gruvbox-baby#63]
The floating diagnostics window has a dark background yielding a pretty confusing view. 

![image](https://github.com/luisiacc/gruvbox-baby/assets/3937658/2b085b3f-4bc8-4502-83fb-f06acebd753f)

With other themes, I can control the background with:

```
:hi Pmenu guibg=#808080  
```
Giving me something like, with `evening` theme, for example:

![image](https://github.com/luisiacc/gruvbox-baby/assets/3937658/fd7b9d22-0bb6-4f23-8f00-eb1d42240649)

However, with gruvbox-baby, this has no effect.

User error?

**Comment by luisiacc** [comment]
Could you try putting this before calling the colorscheme?:

```
vim.g.gruvbox_baby_highlights = {Pmenu = {bg = "#808080"}}
```

**Comment by bitwombat** [comment]
Thanks for the response. Unfortunately, no effect.

**Comment by bitwombat** [comment]
But the colour of the auto-complete window _is_ affected. I don't know how that could be, that the diagnostic window is affect by Pmenu in one them but not gruvbox-baby.

**Comment by bitwombat** [comment]
Turns out that diagnostic menu is `NormalFloat`, but `blue`, `slate`, and other built-in themes _link_ Pmenu to that :angry: 
Confusing!
Thanks for the theme, and thanks for the support.
