### ISSUE TITLE
Brackets highlight inside strings in rust makes text unreadable

### ISSUE THREAD

**Issue by franksl** [luisiacc/gruvbox-baby#64]
Hi,
I'm having a hard time writing strings in rust that contain brackets when the cursor is on a bracket (those highlighted are square brackets, I suppose ;) ):

![image](https://github.com/luisiacc/gruvbox-baby/assets/484004/b2f89020-e45e-48ef-8fa6-e5939a3f93d4)

Thanks,
Frank

**Comment by luisiacc** [comment]
Hi, yeah that's wasn't good at all, fixed it on https://github.com/luisiacc/gruvbox-baby/commit/84c4bbde306ebfd7beb2ff9753b54d77dcd10259
