### ISSUE TITLE
Telescope theme is broken due to missing class reference

### ISSUE THREAD

**Issue by cpfaff** [luisiacc/gruvbox-baby#7]
```
TelescopePromptNormal = { fg = milk, bg = c.medium_gray },
TelescopePromptTitle = { fg = milk, bg = c.soft_yellow },
```

Should reference `c.milk`.

**Comment by cpfaff** [comment]
Fixed it locally. Wow that looks simply awesome.

**Comment by cpfaff** [comment]
One thing I find a bit hard to read is the left hand side yellow background with white text. Maybe dark text on such a light background could be better contrast and thus better to read

**Comment by luisiacc** [comment]
> One thing I find a bit hard to read is the left hand side header which is yellow background with white text. Maybe dark text on such a light background could be better contrast and thus better to read

You're totally right, foreground color should be dark, I didn't notice it because of the `milk` variable error 😉
