### ISSUE TITLE
How to change intensity 

### ISSUE THREAD

**Issue by aFrogThatExists** [luisiacc/gruvbox-baby#71]
Hi! I have not been able to find the way to change the intensity of the palette past the single default. 
I'm happy for all the help I can get.

**Comment by luisiacc** [comment]
Hi there, sorry for the late response, it's the `background_color` part of the docs:

![CleanShot 2023-12-09 at 21 58 55@2x](https://github.com/luisiacc/gruvbox-baby/assets/31720261/bb16b30e-860e-4839-bfc8-552d608d46d8)

**Comment by aFrogThatExists** [comment]
Alright thank you!!
