### ISSUE TITLE
Highlight group broken for nvim-cmp?

### ISSUE THREAD

**Issue by 0xricksanchez** [luisiacc/gruvbox-baby#74]
Hi,

Foremost, love the theme!
I was wondering whether it's a "me-problem" or this is a bug/not implemented. 
Whenever the nvim-cmp snippets pop up, I can never seem to make out which entry I just have highlighted, without spending too much time reading the documentation window on the right.

### With gruvbox-baby

![image](https://github.com/luisiacc/gruvbox-baby/assets/17012133/96498c57-5a6e-4337-9477-56372566104a)

### With another colorscheme e.g. kanagawa-wave

![image](https://github.com/luisiacc/gruvbox-baby/assets/17012133/d1c787ca-3566-4645-b452-95b02a0343be)

I'm using `wezterm` and `nvim 0.9.5`.

From my rudimentary understanding of colors(-schemes), there appears to be a dedicated highlight group for this kind of action somewhere?

**Comment by luisiacc** [comment]
Something is going on with your config, it shows fine to me:

![CleanShot 2024-01-02 at 10 40 01@2x](https://github.com/luisiacc/gruvbox-baby/assets/31720261/19d11fc7-08fd-462e-b815-1ba0ae585602)

**Comment by 0xricksanchez** [comment]
Interesting, guess I'll do some more digging and report back.. Any idea what could cause this behavior?

**Comment by 0xricksanchez** [comment]
Nevermind, had a faulty relic of a `nvim-cmp` configuration lying around that caused this. works fine now.. sorry for the noise
